AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/presentation/handlers/hello-world/helloWorld.helloWorld
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
  GetAll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/presentation/handlers/author/getAll.handle
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        GetAll:
          Type: Api
          Properties:
            Path: /authors
            Method: get

  GetById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: build/presentation/handlers/author/getById.handle
      Runtime: nodejs14.x
      Timeout: 30
      Events:
        GetById:
          Type: Api
          Properties:
            Path: /authors/{id}
            Method: get